server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/smart_attendance
spring.datasource.username=root
spring.datasource.password=Pallavi@9591

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
